services:
  redis:
    image: redis:latest
    container_name: Kapa-readis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    environment:
      - REDIS_MAXMEMORY=256mb
      - REDIS_PASSWORD=kapa

  database:
    image: postgres:latest
    container_name: kapa-database
    ports:
      - "5432:5432"
    volumes:
      - database_data:/var/lib/postgresql
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=docker
      - POSTGRES_DB=kapa

  k6:
    image: grafana/k6:latest
    container_name: kapa-k6
    profiles:
      - test
    network_mode: host
    volumes:
      - ./k6:/scripts
    environment:
      - BASE_URL=http://localhost:4000

volumes:
  redis_data:
  database_data: