import { StyleSheet } from 'react-native';
import { palette, typography } from '@/theme';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: palette.cream },
  content: { width: '100%', maxWidth: 640, alignSelf: 'center', paddingHorizontal: 20, paddingTop: 24, paddingBottom: 40, gap: 20 },
  hero: { flexDirection: 'row', gap: 14, alignItems: 'center' },
  heroIcon: { width: 56, height: 56, borderRadius: 28, backgroundColor: palette.peach, alignItems: 'center', justifyContent: 'center' },
  heroCopy: { flex: 1, gap: 4 },
  title: { ...typography.styles.headlineLgMobile, color: palette.ink },
  subtitle: { ...typography.styles.bodySm, color: palette.inkMuted, lineHeight: 20 },
  feedback: { backgroundColor: '#E8F3EE', borderRadius: 12, padding: 14, borderWidth: 1, borderColor: palette.success },
  feedbackError: { backgroundColor: palette.dangerSoft, borderColor: palette.danger },
  feedbackText: { ...typography.styles.bodySm, color: palette.success, fontFamily: 'PlusJakartaSans-Medium' },
  feedbackErrorText: { color: palette.danger },
  loading: { minHeight: 180, justifyContent: 'center', alignItems: 'center' },
  emptyCard: { backgroundColor: palette.white, borderRadius: 16, paddingHorizontal: 28, paddingVertical: 36, borderWidth: 1, borderColor: palette.line, alignItems: 'center', gap: 10 },
  emptyTitle: { ...typography.styles.headlineMd, color: palette.ink, textAlign: 'center' },
  emptyText: { ...typography.styles.bodySm, color: palette.inkMuted, textAlign: 'center', maxWidth: 300 },
  list: { gap: 12 },
  activityCard: { backgroundColor: palette.white, borderRadius: 16, borderWidth: 1, borderColor: palette.line, padding: 16, gap: 12, shadowColor: palette.orangeDark, shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.04, shadowRadius: 4, elevation: 1 },
  activityHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 },
  typeTag: { backgroundColor: palette.peach, borderRadius: 999, paddingHorizontal: 10, paddingVertical: 6 },
  typeTagText: { ...typography.styles.labelSm, color: palette.denim },
  vacancies: { ...typography.styles.labelSm, color: palette.orangeDark },
  activityTitle: { ...typography.styles.headlineMd, color: palette.ink },
  activityDescription: { ...typography.styles.bodySm, color: palette.inkMuted },
  activityDetails: { gap: 8, paddingTop: 2 },
  detail: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  detailText: { ...typography.styles.bodySm, color: palette.inkSecondary, flexShrink: 1 },
  backButton: { flexDirection: 'row', alignItems: 'center', gap: 8, alignSelf: 'flex-start', paddingVertical: 6, paddingRight: 10 },
  backButtonText: { ...typography.styles.labelMd, color: palette.denim },
  formHeading: { gap: 6 },
  card: { backgroundColor: palette.white, borderRadius: 16, borderWidth: 1, borderColor: palette.line, padding: 16, gap: 14, shadowColor: palette.orangeDark, shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.04, shadowRadius: 4, elevation: 1 },
  section: { ...typography.styles.headlineMd, color: palette.orangeDark },
  fieldLabel: { ...typography.styles.labelMd, color: palette.ink },
  timeRow: { flexDirection: 'row', gap: 12 },
  timeField: { flex: 1 },
  restricted: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 28, gap: 12, backgroundColor: palette.cream },
  restrictedIcon: { width: 60, height: 60, borderRadius: 30, backgroundColor: palette.peach, alignItems: 'center', justifyContent: 'center' },
  restrictedText: { ...typography.styles.bodyMd, color: palette.inkMuted, textAlign: 'center', maxWidth: 330 },
});
